server:
  port: ${PORT:8080}

spring:
  application:
    name: agregador
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  datadog:
    metrics:
      export:
        enabled: true
        api-key: ${DD_API_KEY}
        uri: https://api.us5.datadoghq.com
        step: 15s
        descriptions: false

management.metrics.tags:
  service: agregador
  env: prod
logging:
  level:
    io.micrometer.datadog: INFO
