server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  datadog:
    metrics:
      export:
        enabled: ${DD_METRICS_ENABLED:false}
        api-key: ${DD_API_KEY:}
        application-key: ${DD_APP_KEY:}
        step: 15s
